export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";

export const BASKET_LIST_REQUEST = "BASKET_LIST_REQUEST";
export const BASKET_LIST_SUCCESS = "BASKET_LIST_SUCCESS";
export const BASKET_LIST_FAIL = "BASKET_LIST_FAIL";

export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_REMOVE_ITEM_FAIL = "BASKET_REMOVE_ITEM_FAIL";
